### ISSUE TITLE
tracking issue: Rework command setting

### ISSUE THREAD

**Issue by Mange** [Mange/tydra#6]
The current `command` setting is very limited. Everything must be a single shell script and it's not possible to do any safe argument splitting (which is useful when the action file is generated by another command), changing of environments, etc.

It's also hard to add other settings to the execution, like if it should spawn or exec (#4). Should it wait for the process to finish or not? (#1 + #8)

## Related issues

- [x] #1 - Feature: Fire-and-forget commands
- [x] #4 - Feature: exec commands
- [x] #5 - Magic "quit" return destination is weird
- [x] #8 - ~feature: Command output modes~
- [x] #9 - feature: Wait for confirmation before returning
- [x] #11 - feature: Command specification without implied shell

## Conflicts

- Replacing the process conflicts with most other output settings, like waiting before returning (#9) or where the output should end up (#8).
  - Either handle this using a validator, or make this setup impossible somehow.

## Proposed solution

Solve conflict between `exec` and output settings with a validator first. A more apparent pattern might emerge later, but it makes for a much simpler config file structure.

Change `command` from a `String` into the following object:

```rust
struct Command {
  name: String,
  args: Vec<String>,
  // possible future additions:
  // env_overrides: HashMap<String, String>,
}
```

As a shortcut for the common case of shell scripts, have a `shell` key that expands to a command:

```yaml
title: Show home files
shell: "ls ~"

# Equivalent to
title: Show home files
command:
  name: sh
  args:
    - "-c"
    - "ls ~"
```

Keep other settings on the same level as `Entry` for now to keep the config easy and consistent.

```yaml
title: Show home files
shell: "ls ~"
mode: exec
# output: dedicated # this would fail with a validation error
```

**Comment by Mange** [comment]
`return` is now a boolean or string. (#5)

**Comment by Mange** [comment]
#1, #4, #9 got fixed in #10.

**Comment by Mange** [comment]
Everything is done here!
